
// Generated by Cadence Genus(TM) Synthesis Solution 22.14-s059_1
// Generated on: Aug 31 2026 14:33:30 -03 (Aug 31 2026 17:33:30 UTC)

// Verification Directory fv/sram_dclb 

module booth_radix4(clk, rstn, valid_in, valid_out, a, b, p);
  input clk, rstn, valid_in;
  input [7:0] a, b;
  output valid_out;
  output [15:0] p;
  wire clk, rstn, valid_in;
  wire [7:0] a, b;
  wire valid_out;
  wire [15:0] p;
  wire valid_s1;
  DFFRHQX1 valid_s2_reg(.RN (rstn), .CK (clk), .D (valid_s1), .Q
       (valid_out));
  DFFRHQX1 valid_s1_reg(.RN (rstn), .CK (clk), .D (valid_in), .Q
       (valid_s1));
endmodule

module mem_controller(clk, rstn, start_i, done_i, valid_i, base_i,
     rdata_i, req_o, addr_o, out_byte, out_word, out_valid);
  input clk, rstn, start_i, done_i, valid_i;
  input [15:0] base_i;
  input [31:0] rdata_i;
  output req_o, out_valid;
  output [15:0] addr_o;
  output [7:0] out_byte;
  output [31:0] out_word;
  wire clk, rstn, start_i, done_i, valid_i;
  wire [15:0] base_i;
  wire [31:0] rdata_i;
  wire req_o, out_valid;
  wire [15:0] addr_o;
  wire [7:0] out_byte;
  wire [31:0] out_word;
  wire [3:0] CS;
  wire [1:0] stream_ptr;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_17;
  AOI21X1 g531__2398(.A0 (CS[1]), .A1 (out_valid), .B0 (n_17), .Y
       (req_o));
  NAND2BX1 g532__5107(.AN (CS[2]), .B (CS[0]), .Y (n_17));
  OAI31X1 g693__6260(.A0 (CS[2]), .A1 (CS[0]), .A2 (n_6), .B0 (n_13),
       .Y (n_15));
  SDFFRHQX1 \stream_ptr_reg[1] (.RN (rstn), .CK (clk), .D
       (stream_ptr[1]), .SI (n_8), .SE (out_valid), .Q (stream_ptr[1]));
  OAI31X1 g696__4319(.A0 (n_0), .A1 (n_1), .A2 (n_4), .B0 (n_9), .Y
       (n_14));
  OAI21X1 g697__8428(.A0 (CS[2]), .A1 (n_11), .B0 (CS[0]), .Y (n_13));
  OAI211X1 g698__5526(.A0 (CS[0]), .A1 (n_2), .B0 (n_10), .C0 (n_7), .Y
       (n_12));
  DFFRHQX1 out_valid_reg(.RN (rstn), .CK (clk), .D (n_3), .Q
       (out_valid));
  INVX1 g700(.A (n_10), .Y (n_11));
  NAND2X1 g701__6783(.A (CS[1]), .B (n_4), .Y (n_10));
  DFFRHQX1 \stream_ptr_reg[0] (.RN (rstn), .CK (clk), .D (n_5), .Q
       (stream_ptr[0]));
  OAI2BB1X1 g703__3680(.A0N (n_1), .A1N (n_0), .B0 (CS[2]), .Y (n_9));
  CLKXOR2X1 g704__1617(.A (stream_ptr[0]), .B (stream_ptr[1]), .Y
       (n_8));
  XNOR2X1 g705__2802(.A (n_0), .B (n_17), .Y (n_7));
  MXI2XL g706__1705(.A (valid_i), .B (start_i), .S0 (n_0), .Y (n_6));
  CLKXOR2X1 g707__5122(.A (stream_ptr[0]), .B (out_valid), .Y (n_5));
  NAND2BX1 g708__8246(.AN (stream_ptr[0]), .B (stream_ptr[1]), .Y
       (n_4));
  NOR2X1 g709__7098(.A (n_0), .B (n_17), .Y (n_3));
  DFFRX1 \CS_reg[2] (.RN (rstn), .CK (clk), .D (n_14), .Q (CS[2]), .QN
       (n_2));
  DFFRX1 \CS_reg[0] (.RN (rstn), .CK (clk), .D (n_15), .Q (CS[0]), .QN
       (n_1));
  DFFRX1 \CS_reg[1] (.RN (rstn), .CK (clk), .D (n_12), .Q (CS[1]), .QN
       (n_0));
endmodule

module
     mem_model_ADDR_WIDTH16_DATA_WIDTH32_MEM_WORDS256_LATENCY2_MEM_FILE80h646174612f772e686578(clk,
     rstn, req, valid, addr, rdata);
  input clk, rstn, req;
  input [15:0] addr;
  output valid;
  output [31:0] rdata;
  wire clk, rstn, req;
  wire [15:0] addr;
  wire valid;
  wire [31:0] rdata;
  wire [31:0] latency_counter;
  wire busy, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire sub_54_52_n_0, sub_54_52_n_2, sub_54_52_n_4, sub_54_52_n_6,
       sub_54_52_n_8, sub_54_52_n_10, sub_54_52_n_12, sub_54_52_n_14;
  wire sub_54_52_n_16, sub_54_52_n_18, sub_54_52_n_20, sub_54_52_n_22,
       sub_54_52_n_24, sub_54_52_n_26, sub_54_52_n_28, sub_54_52_n_30;
  wire sub_54_52_n_32, sub_54_52_n_34, sub_54_52_n_36, sub_54_52_n_38,
       sub_54_52_n_40, sub_54_52_n_42, sub_54_52_n_44, sub_54_52_n_46;
  wire sub_54_52_n_48, sub_54_52_n_50, sub_54_52_n_52, sub_54_52_n_54,
       sub_54_52_n_56, sub_54_52_n_58;
  DFFRHQX1 cooldown_reg(.RN (rstn), .CK (clk), .D (n_45), .Q (valid));
  SDFFRHQX1 \latency_counter_reg[0] (.RN (rstn), .CK (clk), .D (busy),
       .SI (n_4), .SE (latency_counter[0]), .Q (latency_counter[0]));
  DFFRHQX1 \latency_counter_reg[1] (.RN (rstn), .CK (clk), .D (n_7), .Q
       (latency_counter[1]));
  SDFFRHQX1 \latency_counter_reg[2] (.RN (rstn), .CK (clk), .D (n_5),
       .SI (n_50), .SE (busy), .Q (latency_counter[2]));
  DFFRHQX1 \latency_counter_reg[3] (.RN (rstn), .CK (clk), .D (n_6), .Q
       (latency_counter[3]));
  DFFRHQX1 \latency_counter_reg[4] (.RN (rstn), .CK (clk), .D (n_28),
       .Q (latency_counter[4]));
  DFFRHQX1 \latency_counter_reg[5] (.RN (rstn), .CK (clk), .D (n_34),
       .Q (latency_counter[5]));
  DFFRHQX1 \latency_counter_reg[6] (.RN (rstn), .CK (clk), .D (n_33),
       .Q (latency_counter[6]));
  DFFRHQX1 \latency_counter_reg[7] (.RN (rstn), .CK (clk), .D (n_32),
       .Q (latency_counter[7]));
  DFFRHQX1 \latency_counter_reg[8] (.RN (rstn), .CK (clk), .D (n_31),
       .Q (latency_counter[8]));
  DFFRHQX1 \latency_counter_reg[9] (.RN (rstn), .CK (clk), .D (n_30),
       .Q (latency_counter[9]));
  DFFRHQX1 \latency_counter_reg[10] (.RN (rstn), .CK (clk), .D (n_29),
       .Q (latency_counter[10]));
  DFFRHQX1 \latency_counter_reg[11] (.RN (rstn), .CK (clk), .D (n_35),
       .Q (latency_counter[11]));
  DFFRHQX1 \latency_counter_reg[12] (.RN (rstn), .CK (clk), .D (n_27),
       .Q (latency_counter[12]));
  DFFRHQX1 \latency_counter_reg[13] (.RN (rstn), .CK (clk), .D (n_26),
       .Q (latency_counter[13]));
  DFFRHQX1 \latency_counter_reg[14] (.RN (rstn), .CK (clk), .D (n_25),
       .Q (latency_counter[14]));
  DFFRHQX1 \latency_counter_reg[15] (.RN (rstn), .CK (clk), .D (n_24),
       .Q (latency_counter[15]));
  DFFRHQX1 \latency_counter_reg[16] (.RN (rstn), .CK (clk), .D (n_23),
       .Q (latency_counter[16]));
  DFFRHQX1 \latency_counter_reg[17] (.RN (rstn), .CK (clk), .D (n_22),
       .Q (latency_counter[17]));
  DFFRHQX1 \latency_counter_reg[18] (.RN (rstn), .CK (clk), .D (n_21),
       .Q (latency_counter[18]));
  DFFRHQX1 \latency_counter_reg[19] (.RN (rstn), .CK (clk), .D (n_13),
       .Q (latency_counter[19]));
  DFFRHQX1 \latency_counter_reg[20] (.RN (rstn), .CK (clk), .D (n_19),
       .Q (latency_counter[20]));
  DFFRHQX1 \latency_counter_reg[21] (.RN (rstn), .CK (clk), .D (n_18),
       .Q (latency_counter[21]));
  DFFRHQX1 \latency_counter_reg[22] (.RN (rstn), .CK (clk), .D (n_17),
       .Q (latency_counter[22]));
  DFFRHQX1 \latency_counter_reg[23] (.RN (rstn), .CK (clk), .D (n_16),
       .Q (latency_counter[23]));
  DFFRHQX1 \latency_counter_reg[24] (.RN (rstn), .CK (clk), .D (n_15),
       .Q (latency_counter[24]));
  DFFRHQX1 \latency_counter_reg[25] (.RN (rstn), .CK (clk), .D (n_14),
       .Q (latency_counter[25]));
  DFFRHQX1 \latency_counter_reg[26] (.RN (rstn), .CK (clk), .D (n_20),
       .Q (latency_counter[26]));
  DFFRHQX1 \latency_counter_reg[27] (.RN (rstn), .CK (clk), .D (n_12),
       .Q (latency_counter[27]));
  DFFRHQX1 \latency_counter_reg[28] (.RN (rstn), .CK (clk), .D (n_11),
       .Q (latency_counter[28]));
  DFFRHQX1 \latency_counter_reg[29] (.RN (rstn), .CK (clk), .D (n_10),
       .Q (latency_counter[29]));
  DFFRHQX1 \latency_counter_reg[30] (.RN (rstn), .CK (clk), .D (n_9),
       .Q (latency_counter[30]));
  DFFRHQX1 \latency_counter_reg[31] (.RN (rstn), .CK (clk), .D (n_8),
       .Q (latency_counter[31]));
  XNOR2X1 g11898__6131(.A (n_1), .B (n_46), .Y (n_47));
  AO21X1 g11900__1881(.A0 (n_1), .A1 (n_2), .B0 (n_45), .Y (n_46));
  NOR4X1 g11901__5115(.A (latency_counter[31]), .B
       (latency_counter[30]), .C (n_1), .D (n_44), .Y (n_45));
  OR4X1 g11902__7482(.A (latency_counter[29]), .B
       (latency_counter[28]), .C (latency_counter[27]), .D (n_43), .Y
       (n_44));
  OR4X1 g11903__4733(.A (latency_counter[26]), .B
       (latency_counter[25]), .C (latency_counter[24]), .D (n_42), .Y
       (n_43));
  OR4X1 g11904__6161(.A (latency_counter[23]), .B
       (latency_counter[22]), .C (latency_counter[21]), .D (n_41), .Y
       (n_42));
  OR4X1 g11905__9315(.A (latency_counter[20]), .B
       (latency_counter[19]), .C (latency_counter[18]), .D (n_40), .Y
       (n_41));
  OR4X1 g11906__9945(.A (latency_counter[17]), .B
       (latency_counter[16]), .C (latency_counter[15]), .D (n_39), .Y
       (n_40));
  OR4X1 g11907__2883(.A (latency_counter[14]), .B
       (latency_counter[13]), .C (latency_counter[12]), .D (n_38), .Y
       (n_39));
  OR4X1 g11908__2346(.A (latency_counter[11]), .B
       (latency_counter[10]), .C (latency_counter[9]), .D (n_37), .Y
       (n_38));
  OR4X1 g11909__1666(.A (latency_counter[8]), .B (latency_counter[7]),
       .C (latency_counter[6]), .D (n_36), .Y (n_37));
  OR4X1 g11926__7410(.A (latency_counter[5]), .B (latency_counter[4]),
       .C (latency_counter[3]), .D (n_3), .Y (n_36));
  AO22X1 g11943__6417(.A0 (latency_counter[11]), .A1 (n_4), .B0 (busy),
       .B1 (n_59), .Y (n_35));
  AO22X1 g11944__5477(.A0 (latency_counter[5]), .A1 (n_4), .B0 (busy),
       .B1 (n_53), .Y (n_34));
  AO22X1 g11945__2398(.A0 (latency_counter[6]), .A1 (n_4), .B0 (busy),
       .B1 (n_54), .Y (n_33));
  AO22X1 g11946__5107(.A0 (latency_counter[7]), .A1 (n_4), .B0 (busy),
       .B1 (n_55), .Y (n_32));
  AO22X1 g11947__6260(.A0 (latency_counter[8]), .A1 (n_4), .B0 (busy),
       .B1 (n_56), .Y (n_31));
  AO22X1 g11948__4319(.A0 (latency_counter[9]), .A1 (n_4), .B0 (busy),
       .B1 (n_57), .Y (n_30));
  AO22X1 g11949__8428(.A0 (latency_counter[10]), .A1 (n_4), .B0 (busy),
       .B1 (n_58), .Y (n_29));
  AO22X1 g11950__5526(.A0 (latency_counter[4]), .A1 (n_4), .B0 (busy),
       .B1 (n_52), .Y (n_28));
  AO22X1 g11951__6783(.A0 (latency_counter[12]), .A1 (n_4), .B0 (busy),
       .B1 (n_60), .Y (n_27));
  AO22X1 g11952__3680(.A0 (latency_counter[13]), .A1 (n_4), .B0 (busy),
       .B1 (n_61), .Y (n_26));
  AO22X1 g11953__1617(.A0 (latency_counter[14]), .A1 (n_4), .B0 (busy),
       .B1 (n_62), .Y (n_25));
  AO22X1 g11954__2802(.A0 (latency_counter[15]), .A1 (n_4), .B0 (busy),
       .B1 (n_63), .Y (n_24));
  AO22X1 g11955__1705(.A0 (latency_counter[16]), .A1 (n_4), .B0 (busy),
       .B1 (n_64), .Y (n_23));
  AO22X1 g11956__5122(.A0 (latency_counter[17]), .A1 (n_4), .B0 (busy),
       .B1 (n_65), .Y (n_22));
  AO22X1 g11957__8246(.A0 (latency_counter[18]), .A1 (n_4), .B0 (busy),
       .B1 (n_66), .Y (n_21));
  AO22X1 g11958__7098(.A0 (latency_counter[26]), .A1 (n_4), .B0 (busy),
       .B1 (n_74), .Y (n_20));
  AO22X1 g11959__6131(.A0 (latency_counter[20]), .A1 (n_4), .B0 (busy),
       .B1 (n_68), .Y (n_19));
  AO22X1 g11960__1881(.A0 (latency_counter[21]), .A1 (n_4), .B0 (busy),
       .B1 (n_69), .Y (n_18));
  AO22X1 g11961__5115(.A0 (latency_counter[22]), .A1 (n_4), .B0 (busy),
       .B1 (n_70), .Y (n_17));
  AO22X1 g11962__7482(.A0 (latency_counter[23]), .A1 (n_4), .B0 (busy),
       .B1 (n_71), .Y (n_16));
  AO22X1 g11963__4733(.A0 (latency_counter[24]), .A1 (n_4), .B0 (busy),
       .B1 (n_72), .Y (n_15));
  AO22X1 g11964__6161(.A0 (latency_counter[25]), .A1 (n_4), .B0 (busy),
       .B1 (n_73), .Y (n_14));
  AO22X1 g11965__9315(.A0 (latency_counter[19]), .A1 (n_4), .B0 (busy),
       .B1 (n_67), .Y (n_13));
  AO22X1 g11966__9945(.A0 (latency_counter[27]), .A1 (n_4), .B0 (busy),
       .B1 (n_75), .Y (n_12));
  AO22X1 g11967__2883(.A0 (latency_counter[28]), .A1 (n_4), .B0 (busy),
       .B1 (n_76), .Y (n_11));
  AO22X1 g11968__2346(.A0 (latency_counter[29]), .A1 (n_4), .B0 (busy),
       .B1 (n_77), .Y (n_10));
  AO22X1 g11969__1666(.A0 (latency_counter[30]), .A1 (n_4), .B0 (busy),
       .B1 (n_78), .Y (n_9));
  AO22X1 g11970__7410(.A0 (latency_counter[31]), .A1 (n_4), .B0 (busy),
       .B1 (n_79), .Y (n_8));
  AO22X1 g11971__6417(.A0 (latency_counter[1]), .A1 (n_4), .B0 (busy),
       .B1 (n_49), .Y (n_7));
  AO22X1 g11972__5477(.A0 (latency_counter[3]), .A1 (n_4), .B0 (busy),
       .B1 (n_51), .Y (n_6));
  OR2X1 g11973__2398(.A (latency_counter[2]), .B (n_2), .Y (n_5));
  NAND3BXL g11974__5107(.AN (latency_counter[1]), .B
       (latency_counter[0]), .C (n_0), .Y (n_3));
  NOR2X4 g11975__6260(.A (busy), .B (n_2), .Y (n_4));
  NOR2BX1 g11976__4319(.AN (req), .B (valid), .Y (n_2));
  INVX1 g12007(.A (latency_counter[2]), .Y (n_0));
  XNOR2X1 sub_54_52_g679__8428(.A (latency_counter[31]), .B
       (sub_54_52_n_58), .Y (n_79));
  OAI2BB1X1 sub_54_52_g680__5526(.A0N (latency_counter[30]), .A1N
       (sub_54_52_n_56), .B0 (sub_54_52_n_58), .Y (n_78));
  OR2X1 sub_54_52_g681__6783(.A (latency_counter[30]), .B
       (sub_54_52_n_56), .Y (sub_54_52_n_58));
  OAI2BB1X1 sub_54_52_g682__3680(.A0N (latency_counter[29]), .A1N
       (sub_54_52_n_54), .B0 (sub_54_52_n_56), .Y (n_77));
  OR2X1 sub_54_52_g683__1617(.A (latency_counter[29]), .B
       (sub_54_52_n_54), .Y (sub_54_52_n_56));
  OAI2BB1X1 sub_54_52_g684__2802(.A0N (latency_counter[28]), .A1N
       (sub_54_52_n_52), .B0 (sub_54_52_n_54), .Y (n_76));
  OR2X1 sub_54_52_g685__1705(.A (latency_counter[28]), .B
       (sub_54_52_n_52), .Y (sub_54_52_n_54));
  OAI2BB1X1 sub_54_52_g686__5122(.A0N (latency_counter[27]), .A1N
       (sub_54_52_n_50), .B0 (sub_54_52_n_52), .Y (n_75));
  OR2X1 sub_54_52_g687__8246(.A (latency_counter[27]), .B
       (sub_54_52_n_50), .Y (sub_54_52_n_52));
  OAI2BB1X1 sub_54_52_g688__7098(.A0N (latency_counter[26]), .A1N
       (sub_54_52_n_48), .B0 (sub_54_52_n_50), .Y (n_74));
  OR2X1 sub_54_52_g689__6131(.A (latency_counter[26]), .B
       (sub_54_52_n_48), .Y (sub_54_52_n_50));
  OAI2BB1X1 sub_54_52_g690__1881(.A0N (latency_counter[25]), .A1N
       (sub_54_52_n_46), .B0 (sub_54_52_n_48), .Y (n_73));
  OR2X1 sub_54_52_g691__5115(.A (latency_counter[25]), .B
       (sub_54_52_n_46), .Y (sub_54_52_n_48));
  OAI2BB1X1 sub_54_52_g692__7482(.A0N (latency_counter[24]), .A1N
       (sub_54_52_n_44), .B0 (sub_54_52_n_46), .Y (n_72));
  OR2X1 sub_54_52_g693__4733(.A (latency_counter[24]), .B
       (sub_54_52_n_44), .Y (sub_54_52_n_46));
  OAI2BB1X1 sub_54_52_g694__6161(.A0N (latency_counter[23]), .A1N
       (sub_54_52_n_42), .B0 (sub_54_52_n_44), .Y (n_71));
  OR2X1 sub_54_52_g695__9315(.A (latency_counter[23]), .B
       (sub_54_52_n_42), .Y (sub_54_52_n_44));
  OAI2BB1X1 sub_54_52_g696__9945(.A0N (latency_counter[22]), .A1N
       (sub_54_52_n_40), .B0 (sub_54_52_n_42), .Y (n_70));
  OR2X1 sub_54_52_g697__2883(.A (latency_counter[22]), .B
       (sub_54_52_n_40), .Y (sub_54_52_n_42));
  OAI2BB1X1 sub_54_52_g698__2346(.A0N (latency_counter[21]), .A1N
       (sub_54_52_n_38), .B0 (sub_54_52_n_40), .Y (n_69));
  OR2X1 sub_54_52_g699__1666(.A (latency_counter[21]), .B
       (sub_54_52_n_38), .Y (sub_54_52_n_40));
  OAI2BB1X1 sub_54_52_g700__7410(.A0N (latency_counter[20]), .A1N
       (sub_54_52_n_36), .B0 (sub_54_52_n_38), .Y (n_68));
  OR2X1 sub_54_52_g701__6417(.A (latency_counter[20]), .B
       (sub_54_52_n_36), .Y (sub_54_52_n_38));
  OAI2BB1X1 sub_54_52_g702__5477(.A0N (latency_counter[19]), .A1N
       (sub_54_52_n_34), .B0 (sub_54_52_n_36), .Y (n_67));
  OR2X1 sub_54_52_g703__2398(.A (latency_counter[19]), .B
       (sub_54_52_n_34), .Y (sub_54_52_n_36));
  OAI2BB1X1 sub_54_52_g704__5107(.A0N (latency_counter[18]), .A1N
       (sub_54_52_n_32), .B0 (sub_54_52_n_34), .Y (n_66));
  OR2X1 sub_54_52_g705__6260(.A (latency_counter[18]), .B
       (sub_54_52_n_32), .Y (sub_54_52_n_34));
  OAI2BB1X1 sub_54_52_g706__4319(.A0N (latency_counter[17]), .A1N
       (sub_54_52_n_30), .B0 (sub_54_52_n_32), .Y (n_65));
  OR2X1 sub_54_52_g707__8428(.A (latency_counter[17]), .B
       (sub_54_52_n_30), .Y (sub_54_52_n_32));
  OAI2BB1X1 sub_54_52_g708__5526(.A0N (latency_counter[16]), .A1N
       (sub_54_52_n_28), .B0 (sub_54_52_n_30), .Y (n_64));
  OR2X1 sub_54_52_g709__6783(.A (latency_counter[16]), .B
       (sub_54_52_n_28), .Y (sub_54_52_n_30));
  OAI2BB1X1 sub_54_52_g710__3680(.A0N (latency_counter[15]), .A1N
       (sub_54_52_n_26), .B0 (sub_54_52_n_28), .Y (n_63));
  OR2X1 sub_54_52_g711__1617(.A (latency_counter[15]), .B
       (sub_54_52_n_26), .Y (sub_54_52_n_28));
  OAI2BB1X1 sub_54_52_g712__2802(.A0N (latency_counter[14]), .A1N
       (sub_54_52_n_24), .B0 (sub_54_52_n_26), .Y (n_62));
  OR2X1 sub_54_52_g713__1705(.A (latency_counter[14]), .B
       (sub_54_52_n_24), .Y (sub_54_52_n_26));
  OAI2BB1X1 sub_54_52_g714__5122(.A0N (latency_counter[13]), .A1N
       (sub_54_52_n_22), .B0 (sub_54_52_n_24), .Y (n_61));
  OR2X1 sub_54_52_g715__8246(.A (latency_counter[13]), .B
       (sub_54_52_n_22), .Y (sub_54_52_n_24));
  OAI2BB1X1 sub_54_52_g716__7098(.A0N (latency_counter[12]), .A1N
       (sub_54_52_n_20), .B0 (sub_54_52_n_22), .Y (n_60));
  OR2X1 sub_54_52_g717__6131(.A (latency_counter[12]), .B
       (sub_54_52_n_20), .Y (sub_54_52_n_22));
  OAI2BB1X1 sub_54_52_g718__1881(.A0N (latency_counter[11]), .A1N
       (sub_54_52_n_18), .B0 (sub_54_52_n_20), .Y (n_59));
  OR2X1 sub_54_52_g719__5115(.A (latency_counter[11]), .B
       (sub_54_52_n_18), .Y (sub_54_52_n_20));
  OAI2BB1X1 sub_54_52_g720__7482(.A0N (latency_counter[10]), .A1N
       (sub_54_52_n_16), .B0 (sub_54_52_n_18), .Y (n_58));
  OR2X1 sub_54_52_g721__4733(.A (latency_counter[10]), .B
       (sub_54_52_n_16), .Y (sub_54_52_n_18));
  OAI2BB1X1 sub_54_52_g722__6161(.A0N (latency_counter[9]), .A1N
       (sub_54_52_n_14), .B0 (sub_54_52_n_16), .Y (n_57));
  OR2X1 sub_54_52_g723__9315(.A (latency_counter[9]), .B
       (sub_54_52_n_14), .Y (sub_54_52_n_16));
  OAI2BB1X1 sub_54_52_g724__9945(.A0N (latency_counter[8]), .A1N
       (sub_54_52_n_12), .B0 (sub_54_52_n_14), .Y (n_56));
  OR2X1 sub_54_52_g725__2883(.A (latency_counter[8]), .B
       (sub_54_52_n_12), .Y (sub_54_52_n_14));
  OAI2BB1X1 sub_54_52_g726__2346(.A0N (latency_counter[7]), .A1N
       (sub_54_52_n_10), .B0 (sub_54_52_n_12), .Y (n_55));
  OR2X1 sub_54_52_g727__1666(.A (latency_counter[7]), .B
       (sub_54_52_n_10), .Y (sub_54_52_n_12));
  OAI2BB1X1 sub_54_52_g728__7410(.A0N (latency_counter[6]), .A1N
       (sub_54_52_n_8), .B0 (sub_54_52_n_10), .Y (n_54));
  OR2X1 sub_54_52_g729__6417(.A (latency_counter[6]), .B
       (sub_54_52_n_8), .Y (sub_54_52_n_10));
  OAI2BB1X1 sub_54_52_g730__5477(.A0N (latency_counter[5]), .A1N
       (sub_54_52_n_6), .B0 (sub_54_52_n_8), .Y (n_53));
  OR2X1 sub_54_52_g731__2398(.A (latency_counter[5]), .B
       (sub_54_52_n_6), .Y (sub_54_52_n_8));
  OAI2BB1X1 sub_54_52_g732__5107(.A0N (latency_counter[4]), .A1N
       (sub_54_52_n_4), .B0 (sub_54_52_n_6), .Y (n_52));
  OR2X1 sub_54_52_g733__6260(.A (latency_counter[4]), .B
       (sub_54_52_n_4), .Y (sub_54_52_n_6));
  OAI2BB1X1 sub_54_52_g734__4319(.A0N (latency_counter[3]), .A1N
       (sub_54_52_n_2), .B0 (sub_54_52_n_4), .Y (n_51));
  OR2X1 sub_54_52_g735__8428(.A (latency_counter[3]), .B
       (sub_54_52_n_2), .Y (sub_54_52_n_4));
  OAI2BB1X1 sub_54_52_g736__5526(.A0N (latency_counter[2]), .A1N
       (sub_54_52_n_0), .B0 (sub_54_52_n_2), .Y (n_50));
  OR2X1 sub_54_52_g737__6783(.A (latency_counter[2]), .B
       (sub_54_52_n_0), .Y (sub_54_52_n_2));
  OAI2BB1X1 sub_54_52_g738__3680(.A0N (latency_counter[0]), .A1N
       (latency_counter[1]), .B0 (sub_54_52_n_0), .Y (n_49));
  OR2X1 sub_54_52_g739__1617(.A (latency_counter[0]), .B
       (latency_counter[1]), .Y (sub_54_52_n_0));
  DFFRX2 busy_reg(.RN (rstn), .CK (clk), .D (n_47), .Q (busy), .QN
       (n_1));
endmodule

module sram_dclb(clk, rstn, enb, done, vld_o, partial_o, mult_o, acc_o,
     result_o, requant_o);
  input clk, rstn, enb, done;
  output vld_o, partial_o;
  output [15:0] mult_o;
  output [31:0] acc_o, result_o;
  output [7:0] requant_o;
  wire clk, rstn, enb, done;
  wire vld_o, partial_o;
  wire [15:0] mult_o;
  wire [31:0] acc_o, result_o;
  wire [7:0] requant_o;
  wire [15:0] addr_W;
  wire [31:0] word_W;
  wire [7:0] size_count;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       UNCONNECTED27, UNCONNECTED28, UNCONNECTED29, UNCONNECTED30;
  wire UNCONNECTED31, UNCONNECTED32, UNCONNECTED33, UNCONNECTED34,
       UNCONNECTED35, UNCONNECTED36, UNCONNECTED37, UNCONNECTED38;
  wire UNCONNECTED39, UNCONNECTED40, UNCONNECTED41, UNCONNECTED42,
       UNCONNECTED43, UNCONNECTED44, UNCONNECTED45, UNCONNECTED46;
  wire UNCONNECTED47, UNCONNECTED48, UNCONNECTED49, UNCONNECTED50,
       UNCONNECTED51, UNCONNECTED52, UNCONNECTED53, UNCONNECTED54;
  wire UNCONNECTED55, UNCONNECTED56, UNCONNECTED57, UNCONNECTED58,
       UNCONNECTED_HIER_Z, UNCONNECTED_HIER_Z0, UNCONNECTED_HIER_Z1,
       UNCONNECTED_HIER_Z2;
  wire UNCONNECTED_HIER_Z3, UNCONNECTED_HIER_Z4, UNCONNECTED_HIER_Z5,
       UNCONNECTED_HIER_Z6, UNCONNECTED_HIER_Z7, UNCONNECTED_HIER_Z8,
       UNCONNECTED_HIER_Z9, UNCONNECTED_HIER_Z10;
  wire UNCONNECTED_HIER_Z11, UNCONNECTED_HIER_Z12,
       UNCONNECTED_HIER_Z13, UNCONNECTED_HIER_Z14,
       UNCONNECTED_HIER_Z15, UNCONNECTED_HIER_Z16,
       UNCONNECTED_HIER_Z17, UNCONNECTED_HIER_Z18;
  wire UNCONNECTED_HIER_Z19, UNCONNECTED_HIER_Z20,
       UNCONNECTED_HIER_Z21, UNCONNECTED_HIER_Z22,
       UNCONNECTED_HIER_Z23, UNCONNECTED_HIER_Z24,
       UNCONNECTED_HIER_Z25, UNCONNECTED_HIER_Z26;
  wire UNCONNECTED_HIER_Z27, UNCONNECTED_HIER_Z28,
       UNCONNECTED_HIER_Z29, UNCONNECTED_HIER_Z30,
       UNCONNECTED_HIER_Z31, UNCONNECTED_HIER_Z32,
       UNCONNECTED_HIER_Z33, UNCONNECTED_HIER_Z34;
  wire UNCONNECTED_HIER_Z35, UNCONNECTED_HIER_Z36,
       UNCONNECTED_HIER_Z37, UNCONNECTED_HIER_Z38,
       UNCONNECTED_HIER_Z39, UNCONNECTED_HIER_Z40,
       UNCONNECTED_HIER_Z41, UNCONNECTED_HIER_Z42;
  wire UNCONNECTED_HIER_Z43, UNCONNECTED_HIER_Z44,
       UNCONNECTED_HIER_Z45, UNCONNECTED_HIER_Z46,
       UNCONNECTED_HIER_Z47, UNCONNECTED_HIER_Z48,
       UNCONNECTED_HIER_Z49, UNCONNECTED_HIER_Z50;
  wire UNCONNECTED_HIER_Z51, UNCONNECTED_HIER_Z52,
       UNCONNECTED_HIER_Z53, UNCONNECTED_HIER_Z54,
       UNCONNECTED_HIER_Z55, UNCONNECTED_HIER_Z56,
       UNCONNECTED_HIER_Z57, UNCONNECTED_HIER_Z58;
  wire UNCONNECTED_HIER_Z59, UNCONNECTED_HIER_Z60,
       UNCONNECTED_HIER_Z61, UNCONNECTED_HIER_Z62,
       UNCONNECTED_HIER_Z63, UNCONNECTED_HIER_Z64,
       UNCONNECTED_HIER_Z65, UNCONNECTED_HIER_Z66;
  wire UNCONNECTED_HIER_Z67, UNCONNECTED_HIER_Z68,
       UNCONNECTED_HIER_Z69, UNCONNECTED_HIER_Z70,
       UNCONNECTED_HIER_Z71, UNCONNECTED_HIER_Z72,
       UNCONNECTED_HIER_Z73, UNCONNECTED_HIER_Z74;
  wire UNCONNECTED_HIER_Z75, UNCONNECTED_HIER_Z76,
       UNCONNECTED_HIER_Z77, UNCONNECTED_HIER_Z78,
       UNCONNECTED_HIER_Z79, n_0, n_1, n_2;
  wire n_3, n_4, n_5, n_6, n_7, n_8, n_9, n_10;
  wire n_11, n_12, n_13, n_14, n_15, partial_r, req_W, valid_W;
  wire vld_W;
  assign requant_o[0] = 1'b0;
  assign requant_o[1] = 1'b0;
  assign requant_o[2] = 1'b0;
  assign requant_o[3] = 1'b0;
  assign requant_o[4] = 1'b0;
  assign requant_o[5] = 1'b0;
  assign requant_o[6] = 1'b0;
  assign requant_o[7] = 1'b0;
  assign result_o[0] = 1'b0;
  assign result_o[1] = 1'b0;
  assign result_o[2] = 1'b0;
  assign result_o[3] = 1'b0;
  assign result_o[4] = 1'b0;
  assign result_o[5] = 1'b0;
  assign result_o[6] = 1'b0;
  assign result_o[7] = 1'b0;
  assign result_o[8] = 1'b0;
  assign result_o[9] = 1'b0;
  assign result_o[10] = 1'b0;
  assign result_o[11] = 1'b0;
  assign result_o[12] = 1'b0;
  assign result_o[13] = 1'b0;
  assign result_o[14] = 1'b0;
  assign result_o[15] = 1'b0;
  assign result_o[16] = 1'b0;
  assign result_o[17] = 1'b0;
  assign result_o[18] = 1'b0;
  assign result_o[19] = 1'b0;
  assign result_o[20] = 1'b0;
  assign result_o[21] = 1'b0;
  assign result_o[22] = 1'b0;
  assign result_o[23] = 1'b0;
  assign result_o[24] = 1'b0;
  assign result_o[25] = 1'b0;
  assign result_o[26] = 1'b0;
  assign result_o[27] = 1'b0;
  assign result_o[28] = 1'b0;
  assign result_o[29] = 1'b0;
  assign result_o[30] = 1'b0;
  assign result_o[31] = 1'b0;
  assign acc_o[0] = 1'b0;
  assign acc_o[1] = 1'b0;
  assign acc_o[2] = 1'b0;
  assign acc_o[3] = 1'b0;
  assign acc_o[4] = 1'b0;
  assign acc_o[5] = 1'b0;
  assign acc_o[6] = 1'b0;
  assign acc_o[7] = 1'b0;
  assign acc_o[8] = 1'b0;
  assign acc_o[9] = 1'b0;
  assign acc_o[10] = 1'b0;
  assign acc_o[11] = 1'b0;
  assign acc_o[12] = 1'b0;
  assign acc_o[13] = 1'b0;
  assign acc_o[14] = 1'b0;
  assign acc_o[15] = 1'b0;
  assign acc_o[16] = 1'b0;
  assign acc_o[17] = 1'b0;
  assign acc_o[18] = 1'b0;
  assign acc_o[19] = 1'b0;
  assign acc_o[20] = 1'b0;
  assign acc_o[21] = 1'b0;
  assign acc_o[22] = 1'b0;
  assign acc_o[23] = 1'b0;
  assign acc_o[24] = 1'b0;
  assign acc_o[25] = 1'b0;
  assign acc_o[26] = 1'b0;
  assign acc_o[27] = 1'b0;
  assign acc_o[28] = 1'b0;
  assign acc_o[29] = 1'b0;
  assign acc_o[30] = 1'b0;
  assign acc_o[31] = 1'b0;
  assign mult_o[0] = 1'b0;
  assign mult_o[1] = 1'b0;
  assign mult_o[2] = 1'b0;
  assign mult_o[3] = 1'b0;
  assign mult_o[4] = 1'b0;
  assign mult_o[5] = 1'b0;
  assign mult_o[6] = 1'b0;
  assign mult_o[7] = 1'b0;
  assign mult_o[8] = 1'b0;
  assign mult_o[9] = 1'b0;
  assign mult_o[10] = 1'b0;
  assign mult_o[11] = 1'b0;
  assign mult_o[12] = 1'b0;
  assign mult_o[13] = 1'b0;
  assign mult_o[14] = 1'b0;
  assign mult_o[15] = 1'b0;
  booth_radix4 u_mult(.clk (clk), .rstn (rstn), .valid_in (valid_W),
       .valid_out (vld_o), .a ({UNCONNECTED_HIER_Z6,
       UNCONNECTED_HIER_Z5, UNCONNECTED_HIER_Z4, UNCONNECTED_HIER_Z3,
       UNCONNECTED_HIER_Z2, UNCONNECTED_HIER_Z1, UNCONNECTED_HIER_Z0,
       UNCONNECTED_HIER_Z}), .b ({UNCONNECTED_HIER_Z14,
       UNCONNECTED_HIER_Z13, UNCONNECTED_HIER_Z12,
       UNCONNECTED_HIER_Z11, UNCONNECTED_HIER_Z10, UNCONNECTED_HIER_Z9,
       UNCONNECTED_HIER_Z8, UNCONNECTED_HIER_Z7}), .p ({UNCONNECTED14,
       UNCONNECTED13, UNCONNECTED12, UNCONNECTED11, UNCONNECTED10,
       UNCONNECTED9, UNCONNECTED8, UNCONNECTED7, UNCONNECTED6,
       UNCONNECTED5, UNCONNECTED4, UNCONNECTED3, UNCONNECTED2,
       UNCONNECTED1, UNCONNECTED0, UNCONNECTED}));
  mem_controller u_weight_mem_ctrl(.clk (clk), .rstn (rstn), .start_i
       (enb), .done_i (UNCONNECTED_HIER_Z15), .valid_i (vld_W), .base_i
       ({UNCONNECTED_HIER_Z31, UNCONNECTED_HIER_Z30,
       UNCONNECTED_HIER_Z29, UNCONNECTED_HIER_Z28,
       UNCONNECTED_HIER_Z27, UNCONNECTED_HIER_Z26,
       UNCONNECTED_HIER_Z25, UNCONNECTED_HIER_Z24,
       UNCONNECTED_HIER_Z23, UNCONNECTED_HIER_Z22,
       UNCONNECTED_HIER_Z21, UNCONNECTED_HIER_Z20,
       UNCONNECTED_HIER_Z19, UNCONNECTED_HIER_Z18,
       UNCONNECTED_HIER_Z17, UNCONNECTED_HIER_Z16}), .rdata_i
       ({UNCONNECTED_HIER_Z63, UNCONNECTED_HIER_Z62,
       UNCONNECTED_HIER_Z61, UNCONNECTED_HIER_Z60,
       UNCONNECTED_HIER_Z59, UNCONNECTED_HIER_Z58,
       UNCONNECTED_HIER_Z57, UNCONNECTED_HIER_Z56,
       UNCONNECTED_HIER_Z55, UNCONNECTED_HIER_Z54,
       UNCONNECTED_HIER_Z53, UNCONNECTED_HIER_Z52,
       UNCONNECTED_HIER_Z51, UNCONNECTED_HIER_Z50,
       UNCONNECTED_HIER_Z49, UNCONNECTED_HIER_Z48,
       UNCONNECTED_HIER_Z47, UNCONNECTED_HIER_Z46,
       UNCONNECTED_HIER_Z45, UNCONNECTED_HIER_Z44,
       UNCONNECTED_HIER_Z43, UNCONNECTED_HIER_Z42,
       UNCONNECTED_HIER_Z41, UNCONNECTED_HIER_Z40,
       UNCONNECTED_HIER_Z39, UNCONNECTED_HIER_Z38,
       UNCONNECTED_HIER_Z37, UNCONNECTED_HIER_Z36,
       UNCONNECTED_HIER_Z35, UNCONNECTED_HIER_Z34,
       UNCONNECTED_HIER_Z33, UNCONNECTED_HIER_Z32}), .req_o (req_W),
       .addr_o ({addr_W[15:8], UNCONNECTED18, UNCONNECTED17,
       UNCONNECTED16, UNCONNECTED15, addr_W[3:0]}), .out_byte
       ({UNCONNECTED26, UNCONNECTED25, UNCONNECTED24, UNCONNECTED23,
       UNCONNECTED22, UNCONNECTED21, UNCONNECTED20, UNCONNECTED19}),
       .out_word (word_W), .out_valid (valid_W));
  mem_model_ADDR_WIDTH16_DATA_WIDTH32_MEM_WORDS256_LATENCY2_MEM_FILE80h646174612f772e686578
       weight_mem(.clk (clk), .rstn (rstn), .req (req_W), .valid
       (vld_W), .addr ({UNCONNECTED_HIER_Z79, UNCONNECTED_HIER_Z78,
       UNCONNECTED_HIER_Z77, UNCONNECTED_HIER_Z76,
       UNCONNECTED_HIER_Z75, UNCONNECTED_HIER_Z74,
       UNCONNECTED_HIER_Z73, UNCONNECTED_HIER_Z72,
       UNCONNECTED_HIER_Z71, UNCONNECTED_HIER_Z70,
       UNCONNECTED_HIER_Z69, UNCONNECTED_HIER_Z68,
       UNCONNECTED_HIER_Z67, UNCONNECTED_HIER_Z66,
       UNCONNECTED_HIER_Z65, UNCONNECTED_HIER_Z64}), .rdata
       ({UNCONNECTED58, UNCONNECTED57, UNCONNECTED56, UNCONNECTED55,
       UNCONNECTED54, UNCONNECTED53, UNCONNECTED52, UNCONNECTED51,
       UNCONNECTED50, UNCONNECTED49, UNCONNECTED48, UNCONNECTED47,
       UNCONNECTED46, UNCONNECTED45, UNCONNECTED44, UNCONNECTED43,
       UNCONNECTED42, UNCONNECTED41, UNCONNECTED40, UNCONNECTED39,
       UNCONNECTED38, UNCONNECTED37, UNCONNECTED36, UNCONNECTED35,
       UNCONNECTED34, UNCONNECTED33, UNCONNECTED32, UNCONNECTED31,
       UNCONNECTED30, UNCONNECTED29, UNCONNECTED28, UNCONNECTED27}));
  NOR4BBX1 g312__2802(.AN (size_count[3]), .BN (n_15), .C
       (size_count[2]), .D (n_14), .Y (partial_o));
  NOR3X1 g313__1705(.A (size_count[1]), .B (size_count[0]), .C
       (partial_r), .Y (n_15));
  OR4X1 g314__5122(.A (size_count[7]), .B (size_count[6]), .C
       (size_count[4]), .D (size_count[5]), .Y (n_14));
  SDFFRHQX1 \size_count_reg[7] (.RN (rstn), .CK (clk), .D
       (size_count[7]), .SI (n_13), .SE (vld_o), .Q (size_count[7]));
  SDFFRHQX1 \size_count_reg[6] (.RN (rstn), .CK (clk), .D
       (size_count[6]), .SI (n_12), .SE (vld_o), .Q (size_count[6]));
  CLKXOR2X1 g315__8246(.A (size_count[7]), .B (n_11), .Y (n_13));
  ADDHX1 g316__7098(.A (size_count[6]), .B (n_9), .CO (n_11), .S
       (n_12));
  SDFFRHQX1 \size_count_reg[5] (.RN (rstn), .CK (clk), .D
       (size_count[5]), .SI (n_10), .SE (vld_o), .Q (size_count[5]));
  ADDHX1 g318__6131(.A (size_count[5]), .B (n_7), .CO (n_9), .S (n_10));
  SDFFRHQX1 \size_count_reg[4] (.RN (rstn), .CK (clk), .D
       (size_count[4]), .SI (n_8), .SE (vld_o), .Q (size_count[4]));
  ADDHX1 g320__1881(.A (size_count[4]), .B (n_5), .CO (n_7), .S (n_8));
  SDFFRHQX1 \size_count_reg[3] (.RN (rstn), .CK (clk), .D
       (size_count[3]), .SI (n_6), .SE (vld_o), .Q (size_count[3]));
  ADDHX1 g322__5115(.A (size_count[3]), .B (n_3), .CO (n_5), .S (n_6));
  SDFFRHQX1 \size_count_reg[2] (.RN (rstn), .CK (clk), .D
       (size_count[2]), .SI (n_4), .SE (vld_o), .Q (size_count[2]));
  ADDHX1 g324__7482(.A (size_count[2]), .B (n_1), .CO (n_3), .S (n_4));
  SDFFRHQX1 \size_count_reg[1] (.RN (rstn), .CK (clk), .D
       (size_count[1]), .SI (n_2), .SE (vld_o), .Q (size_count[1]));
  ADDHX1 g326__4733(.A (size_count[1]), .B (size_count[0]), .CO (n_1),
       .S (n_2));
  SDFFRHQX1 \size_count_reg[0] (.RN (rstn), .CK (clk), .D (vld_o), .SI
       (n_0), .SE (size_count[0]), .Q (size_count[0]));
  DFFRHQX1 partial_r_reg(.RN (rstn), .CK (clk), .D (partial_o), .Q
       (partial_r));
  INVX1 g337(.A (vld_o), .Y (n_0));
endmodule

